development:
  adapter: postgresql
  encoding: unicode
  database: story_development
  pool: 5
  username: story
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: story_test
  pool: 5
  username: story
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: story_production
  pool: 5
  username: story
  password:
